import type { Submission } from "./types";
import { toTagString } from "./tags";

export const mockProfile = {
  firstName: "Tether",
  lastName: "Test",
  email: "TetherTest@gmail.com",
};

export type MockSubmissionSource = "sms" | "email" | "social" | "form";
export type MockSubmission = Submission & { source?: MockSubmissionSource };

export const mockSubmissions: MockSubmission[] = [
  // Mental Health - heavier representation (5 submissions)
  {
    id: "mock-1",
    createdAt: "2026-02-03T09:15:00.000Z",
    updatedAt: "2026-02-03T10:45:00.000Z",
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-234-8891",
    consentToText: true,
    birthdate: "1988-04-12",
    helpTopic: "Counseling",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "I've been struggling with anxiety for the past few months and it's really affecting my daily life. I heard the church has counseling resources and I'd love to connect with someone who can help.",
    tags: toTagString(["mental-health"]),
    source: "sms",
  },
  {
    id: "mock-2",
    createdAt: "2026-02-02T14:30:00.000Z",
    updatedAt: "2026-02-02T16:20:00.000Z",
    firstName: "Marcus",
    lastName: "Thompson",
    email: "marcus.t@outlook.com",
    phoneType: "Mobile",
    phoneNumber: "555-876-2234",
    consentToText: true,
    birthdate: "1975-11-28",
    helpTopic: "Mental health support",
    primaryCampus: "North Campus",
    regularAttender: true,
    additionalDetails:
      "Going through a really dark season right now. Lost my job last month and feeling pretty depressed. Could really use someone to talk to and pray with.",
    tags: toTagString(["mental-health"]),
    source: "form",
  },
  {
    id: "mock-3",
    createdAt: "2026-02-01T19:45:00.000Z",
    updatedAt: "2026-02-02T08:15:00.000Z",
    firstName: "Emily",
    lastName: "Chen",
    email: "emily.chen92@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-443-9901",
    consentToText: true,
    birthdate: "1992-07-03",
    helpTopic: "Stress and anxiety",
    primaryCampus: "Downtown Campus",
    regularAttender: false,
    additionalDetails:
      "New to the church and dealing with a lot of stress from work and family. I keep having panic attacks and don't know what to do. Is there a support group I can join?",
    tags: toTagString(["mental-health"]),
    source: "email",
  },
  {
    id: "mock-4",
    createdAt: "2026-01-30T11:20:00.000Z",
    updatedAt: "2026-01-30T14:50:00.000Z",
    firstName: "David",
    lastName: "Okonkwo",
    email: "dokonkwo@yahoo.com",
    phoneType: "Mobile",
    phoneNumber: "555-221-7788",
    consentToText: true,
    birthdate: "1969-02-14",
    helpTopic: "Grief counseling",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "My mother passed away three weeks ago and I'm having a really hard time. I know she's with the Lord but the grief feels overwhelming. Do you have grief support resources?",
    tags: toTagString(["mental-health", "spiritual-health"]),
    source: "form",
  },
  {
    id: "mock-5",
    createdAt: "2026-01-28T16:10:00.000Z",
    updatedAt: "2026-01-29T09:30:00.000Z",
    firstName: "Jessica",
    lastName: "Ramirez",
    email: "jess.ramirez@icloud.com",
    phoneType: "Mobile",
    phoneNumber: "555-998-3344",
    consentToText: true,
    birthdate: "1995-09-22",
    helpTopic: "Depression",
    primaryCampus: "West Campus",
    regularAttender: true,
    additionalDetails:
      "Been feeling really low lately and struggling to get out of bed some days. I want to stay connected to my small group but it's hard. Can someone check in on me?",
    tags: toTagString(["mental-health"]),
    source: "social",
  },

  // Marriage - moderate representation (4 submissions)
  {
    id: "mock-6",
    createdAt: "2026-02-03T08:00:00.000Z",
    updatedAt: "2026-02-03T11:30:00.000Z",
    firstName: "Michael",
    lastName: "Johnson",
    email: "mjohnson.family@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-112-4455",
    consentToText: true,
    birthdate: "1982-03-17",
    helpTopic: "Marriage counseling",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "My wife and I have been arguing a lot lately about finances and parenting. We love each other but we're in a rough patch. Looking for a Christian marriage counselor recommendation.",
    tags: toTagString(["marriage", "finances"]),
    source: "form",
  },
  {
    id: "mock-7",
    createdAt: "2026-02-01T20:15:00.000Z",
    updatedAt: "2026-02-02T07:45:00.000Z",
    firstName: "Amanda",
    lastName: "Foster",
    email: "amanda.foster@hotmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-667-8899",
    consentToText: true,
    birthdate: "1979-12-05",
    helpTopic: "Relationship help",
    primaryCampus: "North Campus",
    regularAttender: true,
    additionalDetails:
      "Considering separation from my husband. We've been married 15 years but things have gotten really hard. Before we make any decisions I want to talk to a pastor.",
    tags: toTagString(["marriage"]),
    source: "email",
  },
  {
    id: "mock-8",
    createdAt: "2026-01-29T13:40:00.000Z",
    updatedAt: "2026-01-29T17:20:00.000Z",
    firstName: "Brandon",
    lastName: "Williams",
    email: "bwilliams.tx@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-334-5566",
    consentToText: true,
    birthdate: "1990-06-30",
    helpTopic: "Pre-marriage counseling",
    primaryCampus: "Downtown Campus",
    regularAttender: false,
    additionalDetails:
      "Getting engaged soon and want to do this right! Looking for pre-marital counseling resources. My girlfriend and I want to build our marriage on a strong foundation.",
    tags: toTagString(["marriage"]),
    source: "sms",
  },
  {
    id: "mock-9",
    createdAt: "2026-01-26T10:05:00.000Z",
    updatedAt: "2026-01-26T15:40:00.000Z",
    firstName: "Nicole",
    lastName: "Parker",
    email: "nicole.p.parker@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-778-2211",
    consentToText: true,
    birthdate: "1986-01-19",
    helpTopic: "Divorce recovery",
    primaryCampus: "West Campus",
    regularAttender: true,
    additionalDetails:
      "Going through a divorce after my spouse left. Feeling lost and ashamed. Is there a divorce recovery group at the church? I need community right now.",
    tags: toTagString(["marriage", "mental-health"]),
    source: "form",
  },

  // Finances - moderate representation (3 submissions)
  {
    id: "mock-10",
    createdAt: "2026-02-02T11:30:00.000Z",
    updatedAt: "2026-02-02T14:00:00.000Z",
    firstName: "Carlos",
    lastName: "Mendez",
    email: "carlos.mendez.family@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-445-6677",
    consentToText: true,
    birthdate: "1984-08-25",
    helpTopic: "Financial assistance",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "Our family is in a tough spot this month. Unexpected medical bills wiped out our savings and we're behind on rent. I hate to ask but is there any benevolence help available?",
    tags: toTagString(["finances"]),
    source: "form",
  },
  {
    id: "mock-11",
    createdAt: "2026-01-31T15:20:00.000Z",
    updatedAt: "2026-02-01T10:15:00.000Z",
    firstName: "Tanya",
    lastName: "Brooks",
    email: "tanyabrooks@outlook.com",
    phoneType: "Mobile",
    phoneNumber: "555-889-1122",
    consentToText: true,
    birthdate: "1991-04-08",
    helpTopic: "Budgeting help",
    primaryCampus: "North Campus",
    regularAttender: false,
    additionalDetails:
      "Trying to get my finances in order and stop living paycheck to paycheck. Does the church offer any financial literacy classes or workshops? I want to be a better steward.",
    tags: toTagString(["finances"]),
    source: "email",
  },
  {
    id: "mock-12",
    createdAt: "2026-01-27T09:45:00.000Z",
    updatedAt: "2026-01-27T13:30:00.000Z",
    firstName: "Robert",
    lastName: "Kim",
    email: "robkim.engineer@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-223-4455",
    consentToText: true,
    birthdate: "1978-10-11",
    helpTopic: "Debt counseling",
    primaryCampus: "Downtown Campus",
    regularAttender: true,
    additionalDetails:
      "Drowning in credit card debt and feeling hopeless. Made some bad decisions years ago and still paying for them. Would appreciate prayer and any guidance on getting out of this hole.",
    tags: toTagString(["finances", "mental-health"]),
    source: "sms",
  },

  // Spiritual Health - lighter representation (3 submissions)
  {
    id: "mock-13",
    createdAt: "2026-02-03T07:30:00.000Z",
    updatedAt: "2026-02-03T09:00:00.000Z",
    firstName: "Grace",
    lastName: "Anderson",
    email: "grace.a.anderson@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-556-7788",
    consentToText: true,
    birthdate: "1998-05-14",
    helpTopic: "Prayer request",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "Going into surgery next week and I'm scared. Could really use prayer from the prayer team. Also asking for healing and peace for my family during this time.",
    tags: toTagString(["spiritual-health"]),
    source: "sms",
  },
  {
    id: "mock-14",
    createdAt: "2026-01-30T18:50:00.000Z",
    updatedAt: "2026-01-31T08:20:00.000Z",
    firstName: "James",
    lastName: "Washington",
    email: "jameswash@icloud.com",
    phoneType: "Mobile",
    phoneNumber: "555-667-3344",
    consentToText: true,
    birthdate: "1965-09-03",
    helpTopic: "Discipleship",
    primaryCampus: "North Campus",
    regularAttender: true,
    additionalDetails:
      "Been a Christian for 30 years but feel like I've plateaued spiritually. Looking for a mentor or discipleship program to help me grow deeper in my faith.",
    tags: toTagString(["spiritual-health"]),
    source: "form",
  },
  {
    id: "mock-15",
    createdAt: "2026-01-25T12:15:00.000Z",
    updatedAt: "2026-01-25T16:45:00.000Z",
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.m.martinez@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-112-9988",
    consentToText: true,
    birthdate: "2001-11-27",
    helpTopic: "Getting baptized",
    primaryCampus: "West Campus",
    regularAttender: false,
    additionalDetails:
      "I gave my life to Jesus at the Christmas service and I want to get baptized! What do I need to do? I'm so excited to take this step.",
    tags: toTagString(["spiritual-health"]),
    source: "social",
  },

  // Faith Questions - lighter representation (2 submissions)
  {
    id: "mock-16",
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-02-01T13:30:00.000Z",
    firstName: "Kevin",
    lastName: "Nguyen",
    email: "kevin.nguyen.dev@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-778-9900",
    consentToText: true,
    birthdate: "1993-02-08",
    helpTopic: "Questions about faith",
    primaryCampus: "Downtown Campus",
    regularAttender: false,
    additionalDetails:
      "My coworker invited me to church and I've been coming for a few weeks. I have a lot of questions about Christianity and the Bible. Is there someone I could meet with to talk through my doubts?",
    tags: toTagString(["faith-questions"]),
    source: "email",
  },
  {
    id: "mock-17",
    createdAt: "2026-01-28T14:25:00.000Z",
    updatedAt: "2026-01-29T11:10:00.000Z",
    firstName: "Rachel",
    lastName: "Green",
    email: "rachel.green.writes@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-334-2211",
    consentToText: true,
    birthdate: "1989-07-16",
    helpTopic: "Bible questions",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "Reading through the Old Testament and have questions about some of the difficult passages. Would love to join a Bible study or meet with a pastor who can help me understand.",
    tags: toTagString(["faith-questions", "spiritual-health"]),
    source: "form",
  },

  // Other/General (2 submissions)
  {
    id: "mock-18",
    createdAt: "2026-01-29T08:30:00.000Z",
    updatedAt: "2026-01-29T12:00:00.000Z",
    firstName: "Lisa",
    lastName: "Taylor",
    email: "lisa.taylor.mom@gmail.com",
    phoneType: "Mobile",
    phoneNumber: "555-445-1122",
    consentToText: true,
    birthdate: "1980-12-03",
    helpTopic: "Volunteering",
    primaryCampus: "Main Campus",
    regularAttender: true,
    additionalDetails:
      "Want to get more involved at church! I have a background in education and would love to help with children's ministry or wherever I'm needed.",
    tags: toTagString(["other"]),
    source: "form",
  },
  {
    id: "mock-19",
    createdAt: "2026-01-24T17:40:00.000Z",
    updatedAt: "2026-01-25T09:15:00.000Z",
    firstName: "Daniel",
    lastName: "Brown",
    email: "dan.brown.music@outlook.com",
    phoneType: "Mobile",
    phoneNumber: "555-998-7766",
    consentToText: true,
    birthdate: "1996-03-29",
    helpTopic: "Joining a small group",
    primaryCampus: "North Campus",
    regularAttender: false,
    additionalDetails:
      "Just moved to the area and looking to make some connections. Would love to join a young adults small group. Any recommendations for someone in their late 20s?",
    tags: toTagString(["other"]),
    source: "sms",
  },
];

type MockSeedMessage = {
  id: string;
  text: string;
  sender: "user" | "contact";
  timestamp: string;
};

export const mockMessageSeeds: Record<string, MockSeedMessage[]> = {
  "mock-1": [
    {
      id: "mock-1-msg-1",
      text: "Hi Sarah, thank you for reaching out. Anxiety can be really difficult to navigate, but you're not alone. We have several counseling resources available.",
      sender: "user",
      timestamp: "2026-02-03T09:45:00.000Z",
    },
    {
      id: "mock-1-msg-2",
      text: "That means so much. I've been hesitant to ask for help but I know I need it.",
      sender: "contact",
      timestamp: "2026-02-03T10:00:00.000Z",
    },
    {
      id: "mock-1-msg-3",
      text: "I'm sending you info about our licensed Christian counselors. Would you prefer in-person or virtual sessions?",
      sender: "user",
      timestamp: "2026-02-03T10:15:00.000Z",
    },
  ],
  "mock-2": [
    {
      id: "mock-2-msg-1",
      text: "Marcus, I'm so sorry to hear about your job loss. That's incredibly hard. We're here for you.",
      sender: "user",
      timestamp: "2026-02-02T15:00:00.000Z",
    },
    {
      id: "mock-2-msg-2",
      text: "Thank you. Some days are harder than others. I just need to know God hasn't forgotten me.",
      sender: "contact",
      timestamp: "2026-02-02T15:30:00.000Z",
    },
  ],
  "mock-3": [
    {
      id: "mock-3-msg-1",
      text: "Emily, welcome to our church family! I'm glad you reached out. We do have a support group that meets Thursdays.",
      sender: "user",
      timestamp: "2026-02-02T08:00:00.000Z",
    },
  ],
  "mock-4": [
    {
      id: "mock-4-msg-1",
      text: "David, my heart goes out to you. Losing a parent is one of life's hardest experiences. We have a grief share group that starts next month.",
      sender: "user",
      timestamp: "2026-01-30T12:00:00.000Z",
    },
    {
      id: "mock-4-msg-2",
      text: "I think that would help. I've been trying to be strong for my family but I'm falling apart inside.",
      sender: "contact",
      timestamp: "2026-01-30T12:30:00.000Z",
    },
    {
      id: "mock-4-msg-3",
      text: "It's okay to grieve. That's healthy. Would you also like a pastor to call and pray with you this week?",
      sender: "user",
      timestamp: "2026-01-30T13:00:00.000Z",
    },
    {
      id: "mock-4-msg-4",
      text: "Yes please. That would mean so much.",
      sender: "contact",
      timestamp: "2026-01-30T14:00:00.000Z",
    },
  ],
  "mock-5": [
    {
      id: "mock-5-msg-1",
      text: "Hey Jessica, saw your message. Just wanted you to know we care about you and we're praying.",
      sender: "user",
      timestamp: "2026-01-29T09:00:00.000Z",
    },
  ],
  "mock-6": [
    {
      id: "mock-6-msg-1",
      text: "Michael, thanks for being vulnerable. Marriage is hard work but it's worth fighting for. We have some great counselors.",
      sender: "user",
      timestamp: "2026-02-03T09:00:00.000Z",
    },
    {
      id: "mock-6-msg-2",
      text: "We both want to make it work. Just need some tools and outside perspective.",
      sender: "contact",
      timestamp: "2026-02-03T09:30:00.000Z",
    },
    {
      id: "mock-6-msg-3",
      text: "That's a great attitude. I'm connecting you with Pastor Dave who specializes in marriage ministry.",
      sender: "user",
      timestamp: "2026-02-03T10:00:00.000Z",
    },
  ],
  "mock-7": [
    {
      id: "mock-7-msg-1",
      text: "Amanda, thank you for trusting us with something so personal. Before any big decisions, meeting with a pastor is wise.",
      sender: "user",
      timestamp: "2026-02-02T07:30:00.000Z",
    },
  ],
  "mock-8": [
    {
      id: "mock-8-msg-1",
      text: "Brandon! Congratulations on the upcoming engagement! We'd love to help you start strong.",
      sender: "user",
      timestamp: "2026-01-29T14:00:00.000Z",
    },
    {
      id: "mock-8-msg-2",
      text: "Thanks! We're really excited. Want to do things the right way.",
      sender: "contact",
      timestamp: "2026-01-29T14:30:00.000Z",
    },
    {
      id: "mock-8-msg-3",
      text: "Our next pre-marriage class starts in March. I'll send you the registration link!",
      sender: "user",
      timestamp: "2026-01-29T15:00:00.000Z",
    },
  ],
  "mock-9": [
    {
      id: "mock-9-msg-1",
      text: "Nicole, I'm so sorry you're going through this. There is no shame here - only love and support. We do have a divorce recovery group.",
      sender: "user",
      timestamp: "2026-01-26T11:00:00.000Z",
    },
    {
      id: "mock-9-msg-2",
      text: "I was afraid people would judge me. Thank you for saying that.",
      sender: "contact",
      timestamp: "2026-01-26T12:00:00.000Z",
    },
  ],
  "mock-10": [
    {
      id: "mock-10-msg-1",
      text: "Carlos, please don't feel ashamed for asking. This is exactly what the benevolence fund is for. Let me connect you with our care team.",
      sender: "user",
      timestamp: "2026-02-02T12:00:00.000Z",
    },
    {
      id: "mock-10-msg-2",
      text: "God bless you. We've always tried to give when we could. Never thought we'd be on this side of it.",
      sender: "contact",
      timestamp: "2026-02-02T12:30:00.000Z",
    },
    {
      id: "mock-10-msg-3",
      text: "That's what the body of Christ is for - we carry each other. I'll have someone call you today.",
      sender: "user",
      timestamp: "2026-02-02T13:00:00.000Z",
    },
  ],
  "mock-11": [
    {
      id: "mock-11-msg-1",
      text: "Tanya, great question! We have Financial Peace University starting next month. It's been life-changing for so many.",
      sender: "user",
      timestamp: "2026-02-01T10:00:00.000Z",
    },
  ],
  "mock-12": [
    {
      id: "mock-12-msg-1",
      text: "Robert, debt can feel crushing but there is hope. Let's get you connected with our financial coaching ministry.",
      sender: "user",
      timestamp: "2026-01-27T10:30:00.000Z",
    },
    {
      id: "mock-12-msg-2",
      text: "I appreciate that. Feeling pretty embarrassed about it honestly.",
      sender: "contact",
      timestamp: "2026-01-27T11:00:00.000Z",
    },
  ],
  "mock-13": [
    {
      id: "mock-13-msg-1",
      text: "Grace, we're lifting you up in prayer right now. What day is your surgery?",
      sender: "user",
      timestamp: "2026-02-03T07:45:00.000Z",
    },
    {
      id: "mock-13-msg-2",
      text: "Next Tuesday morning. I'm trying to trust God but I'm scared.",
      sender: "contact",
      timestamp: "2026-02-03T08:00:00.000Z",
    },
    {
      id: "mock-13-msg-3",
      text: "It's okay to be scared and trust God at the same time. We'll be praying specifically on Tuesday. You're not alone.",
      sender: "user",
      timestamp: "2026-02-03T08:30:00.000Z",
    },
  ],
  "mock-14": [
    {
      id: "mock-14-msg-1",
      text: "James, that's a beautiful desire to grow deeper. We have a men's discipleship cohort that might be perfect.",
      sender: "user",
      timestamp: "2026-01-31T08:00:00.000Z",
    },
  ],
  "mock-15": [
    {
      id: "mock-15-msg-1",
      text: "Sophia!! We are SO excited for you! Baptism is such a beautiful step. Our next baptism Sunday is February 23rd!",
      sender: "user",
      timestamp: "2026-01-25T13:00:00.000Z",
    },
    {
      id: "mock-15-msg-2",
      text: "That's perfect!! How do I sign up? I want to invite my whole family to come watch!",
      sender: "contact",
      timestamp: "2026-01-25T14:00:00.000Z",
    },
    {
      id: "mock-15-msg-3",
      text: "I'll send you the registration form. We'll also have a quick class the week before to prepare. This is going to be amazing!",
      sender: "user",
      timestamp: "2026-01-25T15:00:00.000Z",
    },
  ],
  "mock-16": [
    {
      id: "mock-16-msg-1",
      text: "Kevin, we love that you're asking questions! Doubt is often the beginning of real faith. Pastor Mike leads an Alpha course for seekers.",
      sender: "user",
      timestamp: "2026-02-01T11:00:00.000Z",
    },
    {
      id: "mock-16-msg-2",
      text: "That sounds perfect. I have a lot of intellectual hangups but I'm genuinely curious.",
      sender: "contact",
      timestamp: "2026-02-01T12:00:00.000Z",
    },
  ],
  "mock-17": [
    {
      id: "mock-17-msg-1",
      text: "Rachel, the Old Testament can be challenging! We have a women's Bible study that's going through it right now with great discussion.",
      sender: "user",
      timestamp: "2026-01-29T11:00:00.000Z",
    },
  ],
  "mock-18": [
    {
      id: "mock-18-msg-1",
      text: "Lisa, we'd love to have you serve! With your education background, kids ministry would love you. Want me to connect you with the director?",
      sender: "user",
      timestamp: "2026-01-29T09:00:00.000Z",
    },
    {
      id: "mock-18-msg-2",
      text: "Yes please! I've been praying about how to use my gifts and this feels right.",
      sender: "contact",
      timestamp: "2026-01-29T10:00:00.000Z",
    },
  ],
  "mock-19": [
    {
      id: "mock-19-msg-1",
      text: "Welcome to the area, Daniel! We have several young adult groups. What night works best for you?",
      sender: "user",
      timestamp: "2026-01-25T09:00:00.000Z",
    },
  ],
};
